name: ${PROJECT_NAME}

networks:
  proxy:
    name: ${PROXY:-proxy}
    external: TRUE

volumes:
  site-models:

services:
  ocha_ai_helper:
    image: public.ecr.aws/unocha/$IMAGE_NAME:$IMAGE_TAG
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    environment:
      ENVIRONMENT:
      VIRTUAL_HOST: ${SITE_DOMAIN}
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: ${PROXY:-proxy}
      HTTPS_METHOD: noredirect
    volumes:
      - "site-models:/opt/models:rw"
      - "../html:/srv/www/html"
    labels:
      caddy: ${SITE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams}}"
    expose:
      - "80"
    networks:
      proxy:
